### ISSUE TITLE
Different image types

### ISSUE THREAD

**Issue by franciscosenae** [mdbloice/Augmentor#211]
Hi,

I am currently working with the ISIC-2017 dataset, that contains images as .jpg and masks as .png

When adding the ground truth masks, the output is:

> 0 ground truth image(s) found.

If I convert the image to .jpg, this problem disappears.
Is is possible to add support to .png?

Thank you,
Francisco

**Comment by joys8998** [comment]
The problem is not the support of .png files since the library works fine with .png files but the extension file in images and groundtrith has to be the same.

From the documentation:

an image titled cat321.jpg will match with the image cat321.jpg in the ground_truth_directory. The function respects each image’s label, therefore the image named cat321.jpg with the label cat will match the image cat321.jpg in the subdirectory cat relative to ground_truth_directory.

**Comment by franciscosenae** [comment]
Thank you very much!

Though it would be better to match through the same name, independently of the extension in use.
