### ISSUE TITLE
Incompatible with numpy >= 1.20 due to use of type aliases.

### ISSUE THREAD

**Issue by jsilter** [mdbloice/Augmentor#250]
See https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

Type aliases only used in two places (that I could find).

**Comment by mdbloice** [comment]
Oh yes, you're right. Thanks for pointing this out. 

I also noticed that I used `np.uint8` a fair bit here and there (mostly in the tests), but it seems that things like `np.uint8` and `np.float16` etc. will not deprecated in order to allow for control of precision. So those can be kept. The two you found seem to be the only relevant ones that would need to be changed.
